import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f5f5f5',
    },
    contentContainer: {
        padding: 20,
        paddingBottom: 40,
    },
    regenerateButton: {
        backgroundColor: '#ff3b30',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 8,
        marginBottom: 20,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    regenerateButtonDisabled: {
        backgroundColor: '#ffb3ae',
        opacity: 0.7,
    },
    regenerateButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '600',
    },
    qrSection: {
        backgroundColor: 'white',
        borderRadius: 12,
        padding: 20,
        marginBottom: 20,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#333',
        marginBottom: 20,
    },
    qrContainer: {
        padding: 20,
        backgroundColor: 'white',
        borderRadius: 8,
    },
    qrPlaceholder: {
        width: 200,
        height: 200,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#f0f0f0',
    },
    qrPlaceholderText: {
        color: '#999',
        fontSize: 14,
    },
    keySection: {
        gap: 20,
        paddingBottom: 20,
    },
    keyContainer: {
        backgroundColor: 'white',
        borderRadius: 12,
        padding: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    keyHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    keyLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
    },
    copyButton: {
        backgroundColor: '#007AFF',
        paddingHorizontal: 16,
        paddingVertical: 6,
        borderRadius: 6,
    },
    copyButtonText: {
        color: 'white',
        fontSize: 14,
        fontWeight: '500',
    },
    keyInput: {
        backgroundColor: '#f9f9f9',
        borderWidth: 1,
        borderColor: '#e0e0e0',
        borderRadius: 8,
        padding: 12,
        fontSize: 12,
        fontFamily: 'monospace',
        color: '#333',
        minHeight: 60,
    },
    privateKeyInput: {
        minHeight: 80,
    },
    privateKeyNote: {
        fontSize: 12,
        color: '#666',
        marginTop: 8,
        fontStyle: 'italic',
    },
    warningSection: {
        backgroundColor: '#fff3cd',
        borderRadius: 12,
        padding: 16,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: '#ffc107',
    },
    warningText: {
        fontSize: 14,
        color: '#856404',
        lineHeight: 20,
        textAlign: 'center',
    },
    languageOptions: {
        gap: 8,
    },
    languageOption: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 8,
        backgroundColor: '#f9f9f9',
        borderWidth: 1,
        borderColor: '#e0e0e0',
    },
    languageOptionActive: {
        backgroundColor: '#007AFF',
        borderColor: '#007AFF',
    },
    languageOptionText: {
        fontSize: 16,
        color: '#333',
        fontWeight: '500',
    },
    languageOptionTextActive: {
        color: 'white',
        fontWeight: '600',
    },
    checkmark: {
        fontSize: 18,
        color: 'white',
        fontWeight: 'bold',
    },
});
